name: .NET Core 2

on:
  release:
    types: [published, prereleased]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5

    - name: Nuget restore
      run: nuget restore packmule.sln
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: MSBuild
      run: msbuild .\packmule\packmule.csproj
    
    #- name: Zip build
      #run: zip -r .\packmule\packmule\bin\debug.zip .\packmule\packmule\bin\debug\
      #uses: montudor/action-zip@v0.1.0
      #with:
        #args: zip -qq -r .\packmule\packmule\bin\debug.zip .\packmule\packmule\bin\debug\
        
      
    
    - name: Upload to release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          README.md
          .\packmule\PublishOutput\packmule.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
