name: .NET Core

on:
  release:
    types: [published, prereleased]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Nuget restore
      run: nuget restore .\packmule.sln
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: MSBuild
      run: msbuild .\packmule\packmule.csproj
    
    - name: Zip build
      run: |
        zip .\packmule\packmule\bin\debug.zip .\packmule\packmule\bin\debug\
      #uses: montudor/action-zip@v0.1.0
      #with:
        #args: zip -qq -r .\packmule\packmule\bin\debug.zip .\packmule\packmule\bin\debug\
        
      
    
    - name: Upload to release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          README.md
          .\packmule\packmule\bin\debug.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
