name: .NET Core

on:
  release:
  push:
    types: [published, prereleased]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
      
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Nuget Restore
      run: nuget restore .\packmule.sln
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.500
    - name: Build with dotnet
      run: dotnet build --configuration Release
